<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE simulation [
    <!ELEMENT simulation (graph, events)>
    <!ATTLIST simulation finalinst CDATA #REQUIRED>
    <!ATTLIST simulation antcolsize CDATA #REQUIRED>
    <!ATTLIST simulation plevel CDATA #REQUIRED>
    <!ELEMENT graph (node+)>
    <!ATTLIST graph nbnodes CDATA #REQUIRED>
    <!ATTLIST graph nestnode CDATA #REQUIRED>
    <!ELEMENT node (weight*)>
    <!ATTLIST node nodeidx CDATA #REQUIRED>
    <!ELEMENT weight (#PCDATA)>
    <!ATTLIST weight targetnode CDATA #REQUIRED>
    <!ELEMENT events (move, evaporation)>
    <!ELEMENT move EMPTY>
    <!ATTLIST move alpha CDATA #REQUIRED>
    <!ATTLIST move beta CDATA #REQUIRED>
    <!ATTLIST move delta CDATA #REQUIRED>
    <!ELEMENT evaporation EMPTY>
    <!ATTLIST evaporation eta CDATA #REQUIRED>
    <!ATTLIST evaporation rho CDATA #REQUIRED>
]>
<simulation finalinst="300.0" antcolsize="1" plevel="0.5">
    <graph nbnodes="5" nestnode="1">
        <node nodeidx="1">
            <weight targetnode="2">3</weight>
            <weight targetnode="3">6</weight>
            <weight targetnode="4">6</weight>
            <weight targetnode="5">2</weight>
        </node>
        <node nodeidx="2">
            <weight targetnode="3">3</weight>
            <weight targetnode="4">2</weight>
            <weight targetnode="5">5</weight>
        </node>
        <node nodeidx="3">
        </node>
        <node nodeidx="4">
            <weight targetnode="5">1</weight>
        </node>
    </graph>
    <events>
        <move alpha="1.0" beta="1.0" delta="0.2"/>
        <evaporation eta="10" rho="0.1"/>
    </events>
</simulation>